### ISSUE TITLE
Can't create Record<Id, any>

### ISSUE THREAD

**Issue by JBYoshi** [screepers/typed-screeps#142]
### Expected Behavior

Since `Id` objects are just strings, I should be able to create a `Record` using `Id`s as keys.

### Actual Behavior

I get the following error:

```
Type 'Id<Creep>' does not satisfy the constraint 'string | number | symbol'.
  Type 'Id<Creep>' is not assignable to type 'string'.
```
### Sample code (if available)

```ts
var data: Record<Id<Creep>, number> = {};
```

### Your Environment

- Node.js version: 12.13.0
- TypeScript version: 3.6.4
- {`typed-screeps` or `@types/screeps` delete as appropriate} version: https://github.com/screepers/typed-screeps/commit/be96ea9f377dadf00fbddf430f88e44ee01e64b8

**Comment by pyrodogg** [comment]
Game object id's were re-typed as a result of #92, which has been planned for some time. Since preparations are being made for a major version release, I thought it would be a good time to include this breaking change. 

Unfortunately, object keys must be of type `sting | number | symbol` so `Id<Creep>` can't be used as the key type for a Record.

You can still make a record with a string key, and explicitly type assert the key values to strings.

```TypeScript
const data: Record<string, number> = {};
data[creep.id as string] = 42; // type assert Id<Creep> to string
```

**Comment by eduter** [comment]
I don't know what's the use case, but `const data = new Map<Id<Creep>, number>()` may also be an option.

**Comment by pyrodogg** [comment]
Yes, `Map` seems like a much better way to handle these now as Map keys don't have to be primitives.

```TypeScript
    const creepStat = new Map<Id<Creep>, number>();
    const creepId: Id<Creep> = "123";

    creepStat.set(creepId, 123);

    creepStat.forEach((number, id) => { 
        const creep = Game.getObjectById(key); // type of Creep | null

        if (creep) {
            // do something?
        }
    });
```

**Comment by JBYoshi** [comment]
What about places where the ID is used as a key in memory?

**Comment by pyrodogg** [comment]
Cast to string or number as index types can only be `string | number | symbol` types.
