### ISSUE TITLE
Problem due installation

### ISSUE THREAD

**Issue by DrSnail** [screepers/typed-screeps#156]
I am a little bit confused about installation. Is the installation section comprehensive? If i follow every single step everything will work? 
But how i could get the main.js file? I tried npm run compile, but there is no any main.js. Sry for silly question

**Comment by tcdejong** [comment]
These are TypeScript declarations. Installing them from NPM with `npm install @types/screeps` will automatically get the `.ts` file - all you really need - added to your `node modules` folder. That's all there is to it. If it's in the same directory as your code (or a subdirectory of it) your IDE and linter should automatically find it. 

That said, I see you also made an issue in the `screeps-typescript-starter`, which already includes this package in its dependencies. You don't need to manually install this if you use the starter kit.

**Comment by pyrodogg** [comment]
Since there haven't been more reports of issue since screepers/screeps-typescript-starter#118 was closed I'm also closing this issue. 

If you still have general questions about using TypeScript with screeps I recommend reaching out to the #typescript channel on the screeps slack https://chat.screeps.com/
