### ISSUE TITLE
Spawn.renewCreep() formulas are incorrect

### ISSUE THREAD

**Issue by pathurs** [screepers/typed-screeps#157]
### Expected Behavior

Increase the remaining time to live of the target creep. The target should be at adjacent square. The spawn should not be busy with the spawning process. Each execution increases the creep's timer by amount of ticks according to this formula:

`floor(600/body_size)`

Energy required for each execution is determined using this formula:

`ceil(creep_cost/2.5/body_size)`

Renewing a creep removes all of its boosts.

### Actual Behavior

https://github.com/screepers/typed-screeps/blob/master/src/spawn.ts#L115-L127
    /**
     * Increase the remaining time to live of the target creep.
     *
     * The target should be at adjacent square.
     *
     * The spawn should not be busy with the spawning process.
     *
     * Each execution increases the creep's timer by amount of ticks according to this formula: floor(500/body_size).
     *
     * Energy required for each execution is determined using this formula: ceil(creep_cost/3/body_size).
     * @param target The target creep object.
     */
    renewCreep(target: Creep): ScreepsReturnCode;

**Comment by tcdejong** [comment]
Your expected behavior is in line with https://docs.screeps.com/api/#StructureSpawn.renewCreep

However, the Screeps engine [does it differently.](https://github.com/screeps/engine/blob/ptr/src/processor/intents/spawns/renew-creep.js#L28). New life is:  
`var effect = Math.floor(C.SPAWN_RENEW_RATIO * C.CREEP_LIFE_TIME / C.CREEP_SPAWN_TIME / target.body.length);`  

With constants:

- `CREEP_LIFE_TIME: 1500,`
- `CREEP_SPAWN_TIME: 3,`
- `SPAWN_RENEW_RATIO: 1.2,`

Resolves to `1.2*1500/3/target.body.length` = `600/target.body.length`

[Energy cost](https://github.com/screeps/engine/blob/ptr/src/processor/intents/spawns/renew-creep.js#L33) is `C.SPAWN_RENEW_RATIO * utils.calcCreepCost(target.body) / C.CREEP_SPAWN_TIME / target.body.length`, or `body_cost / (3 / 1.2) / body_length`, which correctly resolves to `body_cost / 2.5 / body_length`.  

Both formulas are currently described as they are processed by the engine. 

Alternatively, replace the number altogether and shove the constants in instead (though that might be inconsistent with how we do it elsewhere in these typings?)

**Comment by tcdejong** [comment]
Created PR #158 for to update the docstring.

**Comment by pyrodogg** [comment]
#158 has been merged which updates the description. This will be included in next push to Definitely Typed.
