### ISSUE TITLE
Rollback breaking change on `Game.getObjectById` to follow Semantic Versioning

### ISSUE THREAD

**Issue by DiamondMofeng** [screepers/typed-screeps#223]
### What happened

There is a breaking change to Game.getObjectById in the [release 3.3.0](https://github.com/screepers/typed-screeps/releases/tag/v3.3.0), but only MINOR version was increased.

Over the past few months I've seen many players complains about this. Most of their old codes failed to pass Typescript's type checking because of the breaking change on `Game.getObjectById`.

### What should we do

Publish a new minor version which brings `Game.getObjectById(id:string)` back.

Then we could publish a new major version to enable the strict check on type of Id.

**Comment by pyrodogg** [comment]
I agree. This was my mistake in handling and packaging the update. 

Unfortunately I don't have the time to jump through pushing a clean 3.3.1 release and then pushing the update to 4.0.0. That would definitely be proper under the guidelines of Semantic Versioning. I feel odd for indicating any major updates to the game since it's rare something significant happens and I let that distract me. 

We've made contact over Discord now about access, but to note again if you make any PRs in the meantime, ping me on Discord and I should be able to follow-up on them clearer. If you do get access soon this would be a good point to jump in going through the process of pushing updates to DefinitelyTyped.

**Comment by DiamondMofeng** [comment]
I find that there are other breaking changes like #211, #217. So I think we should checkout to a new branch from 926712d to solve this.
