### ISSUE TITLE
How are you supposed to use typed memory?

### ISSUE THREAD

**Issue by fuchsnj** [screepers/typed-screeps#27]
The new "typed memory" doesn't seem to be working for me.

The `CreepMemory` is an empty interface, so it lets you set arbitrary data, but reading gets something like
```
TS2339: Property 'taskMemory' does not exist on type 'CreepMemory'.
```

The README implies you can just define an interface also called `CreepMemory` but that does nothing.

how are you actually supposed to use this?

**Comment by fuchsnj** [comment]
... apparently you have to put the interface in a `*.d.ts` file.

**Comment by apemanzilla** [comment]
To clarify, it doesn't necessarily have to be in a `.d.ts` file, it just has to be an ambient declaration. For example, in your `.ts` file (with at least one import or export) you can use `declare global { interface CreepMemory { ... } }` to accomplish the same effect.

**Comment by JLLeitschuh** [comment]
Just for anyone in the future looking for a more complete solution:
```typescript
declare global { interface CreepMemory {
  [key:string]: any
} }
```

**Comment by Herbo4** [comment]
I'm having a hard time using this currently; the installed node_module for Screeps types comes with types in a global.d.ts and it looks like declaring the interface as a global:
`declare namespace Cartograph {
    interface Cartograph {
        //containing object
        //current roomName
        cartograph: Guide
    }
}`
(this breaks my local reference to the interface if I don't repeat the interface in a local scope as seen below)
does not work, and nor does writing the interface out in my own types.d.ts sitting in src/ :
`export interface Cartograph {
    //containing object
    //current roomName
    cartograph: Guide
}`

And neither resolves my problem trying to make something like this happen:
`global.Cartograph //Property 'Cartograph' does not exist on type 'Global'.`
`Cartograph.chart//Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof Cartograph'.

Ideally, I'd like to make my Cartograph class and interface in a single file, Cartograph.ts, and have my types.d.ts only handle interfaces that don't belong to specific classes. Can someone show me the error of my ways?
