### ISSUE TITLE
invalid declaration of FindTypes lookup interface

### ISSUE THREAD

**Issue by Arcath** [screepers/typed-screeps#39]
As opened by @smhxx on the DT repo

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23030

`-106` or `FIND_DROPPED_ENERGY` is actually deprecated (https://screeps.com/forum/post/2787) so we can remove it. At the same time, we should add a warning to `FIND_DROPPED_ENERGY` to let users know its deprecated.

**Comment by smhxx** [comment]
Oh! Well, isn't that convenient? lol

I would say that is probably a good idea, given that it seems to be majorly screwing up the lookup types for the "find" functions. Not really sure why they thought it was a good idea to have it be a negative value in the first place, to be honest. xD

**Comment by Arcath** [comment]
I think `106` was `FIND_DROPPED_ENERGY` before other resources existed. They changed `FIND_DROPPED_ENERGY` to `-106` and made a new constant `FIND_DROPPED_RESOURCES` for `106` so that things worked as expected. `FIND_DROPPED_ENERGY` actually finds all resources so it's not really usable.

We need a test to catch this as well.

**Comment by smhxx** [comment]
Ah, interesting. I hadn't been following updates very closely so I wasn't aware of the story behind the -106 value. That makes significantly more sense if they moved the constant to some junk value to avoid breaking people's code by removing it entirely.

**Comment by Varatnar** [comment]
I am unsure as to where exactly to write this down, but this issue was only partially fixed. By that i mean that while a comment was added to the `FIND_DROPPED_ENERGY` const, it did not add a deprecated tag.

I'm going to shoot this here, wait a few day and look up on how to make a pull request later if no one picks this up.

```ts
/** @deprecated `FIND_DROPPED_ENERGY` is deprecated the return value is the same as `FIND_DROPPED_RESOURCES` */
declare const FIND_DROPPED_ENERGY: -106;
```
I'd highly suggest adding the deprecated tag. While not major, it did take me a few min of fiddling to realize that the value should not be used.
